name: Deploy to Deta-Space
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Deta-Space credential 
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: ${{ secrets.DETA_SPACE_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          space_push: true
          




